package subdomain_takeover

var services = []Service{
    {
        Service:   "AWS/Elastic Beanstalk",
        Cname:     []string{"elasticbeanstalk.com"},
        Fingerprint: []string{"NXDOMAIN"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "AWS/S3",
        Cname:     []string{"s3.amazonaws.com"},
        Fingerprint: []string{"The specified bucket does not exist"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),

    },
    {
        Service:   "Agile CRM",
        Cname:     []string{"agilecrm.com"},
        Fingerprint: []string{"Sorry, this page is no longer available."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Airee.ru",
        Cname:     []string{"airee.ru"},
        Fingerprint: []string{"Ошибка 402. Сервис Айри.рф не оплачен"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Anima",
        Cname:     []string{"animaapp.io"},
        Fingerprint: []string{"The page you were looking for does not exist."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Bitbucket",
        Cname:     []string{"bitbucket.io"},
        Fingerprint: []string{"Repository not found"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Campaign Monitor",
        Cname:     []string{},
        Fingerprint: []string{"Trying to access your account?"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Canny",
        Cname:     []string{},
        Fingerprint: []string{"Company Not Found. There is no such company. Did you enter the right URL?"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Cargo Collective",
        Cname:     []string{},
        Fingerprint: []string{"404 Not Found"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Digital Ocean",
        Cname:     []string{},
        Fingerprint: []string{"Domain uses DO name servers with no records in DO."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Discourse",
        Cname:     []string{"trydiscourse.com"},
        Fingerprint: []string{"NXDOMAIN"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Gemfury",
        Cname:     []string{"furyns.com"},
        Fingerprint: []string{"404: This page could not be found."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Getresponse",
        Cname:     []string{},
        Fingerprint: []string{"With GetResponse Landing Pages, lead generation has never been easier"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Ghost",
        Cname:     []string{"ghost.io"},
        Fingerprint: []string{"Site unavailable. Failed to resolve DNS path for this host"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "HatenaBlog",
        Cname:     []string{"hatenablog.com"},
        Fingerprint: []string{"404 Blog is not found"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Help Juice",
        Cname:     []string{"helpjuice.com"},
        Fingerprint: []string{"We could not find what you're looking for."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Help Scout",
        Cname:     []string{"helpscoutdocs.com"},
        Fingerprint: []string{"No settings were found for this company:"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Helprace",
        Cname:     []string{"helprace.com"},
        Fingerprint: []string{"HTTP_STATUS=301"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "JetBrains",
        Cname:     []string{"youtrack.cloud"},
        Fingerprint: []string{"is not a registered InCloud YouTrack"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "LaunchRock",
        Cname:     []string{"launchrock.com"},
        Fingerprint: []string{"HTTP_STATUS=500"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Microsoft Azure",
        Cname:     []string{
            "cloudapp.net",
            "cloudapp.azure.com",
            "azurewebsites.net",
            "blob.core.windows.net",
            "cloudapp.azure.com",
            "azure-api.net",
            "azurehdinsight.net",
            "azureedge.net",
            "azurecontainer.io",
            "database.windows.net",
            "azuredatalakestore.net",
            "search.windows.net",
            "azurecr.io",
            "redis.cache.windows.net",
            "azurehdinsight.net",
            "servicebus.windows.net",
            "visualstudio.com",
        },
        Fingerprint: []string{"NXDOMAIN"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Ngrok",
        Cname:     []string{"ngrok.io"},
        Fingerprint: []string{"Tunnel .*ngrok.io not found"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Pantheon",
        Cname:     []string{},
        Fingerprint: []string{"404 error unknown site!"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Pingdom",
        Cname:     []string{},
        Fingerprint: []string{"Sorry, couldn't find the status page"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Readme.io",
        Cname:     []string{"readme.io"},
        Fingerprint: []string{"The creators of this project are still working on making everything perfect!"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Readthedocs",
        Cname:     []string{},
        Fingerprint: []string{"The link you have followed or the URL that you entered does not exist."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Short.io",
        Cname:     []string{},
        Fingerprint: []string{"Link does not exist"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "SmartJobBoard",
        Cname:     []string{"52.16.160.97"},
        Fingerprint: []string{"This job board website is either expired or its domain name is invalid."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Smugsmug",
        Cname:     []string{},
        Fingerprint: []string{},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Strikingly",
        Cname:     []string{"s.strikinglydns.com"},
        Fingerprint: []string{"PAGE NOT FOUND."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Surge.sh",
        Cname:     []string{"na-west1.surge.sh"},
        Fingerprint: []string{"project not found"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "SurveySparrow",
        Cname:     []string{"surveysparrow.com"},
        Fingerprint: []string{"Account not found."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Uberflip",
        Cname:     []string{"read.uberflip.com"},
        Fingerprint: []string{"The URL you've accessed does not provide a hub."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Uptimerobot",
        Cname:     []string{"stats.uptimerobot.com"},
        Fingerprint: []string{"page not found"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Wordpress",
        Cname:     []string{"wordpress.com"},
        Fingerprint: []string{"Do you want to register .*wordpress.com?"},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    {
        Service:   "Worksites",
        Cname:     []string{"worksites.net", "69.164.223.206"},
        Fingerprint: []string{"Hello! Sorry, but the website you’re looking for doesn’t exist."},
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    //  edge cases
    /*    {
			  //The requirements for a site to be vulnerable are:
        //The apex has been pointed to GitHub Pages;
        //The site uses something like cPanel that leaves dangling CNAMEs like ftp. pointing to that apex;
        //The site owner has not followed the GitHub recommendation to "verify" the domain name with a TXT record to prevent other people from using subdomains.
        Service:   "GitHub",
        Cname:     []string{"github.io", "github.map.fastly.net"},
        Fingerprint: []string{
            "There isn't a GitHub Pages site here.",
            "For root URLs (like http://example.com/) you must provide an index.html file",
        },
        Status:  string{"Edge Case"},
        Vulnerable: bool(true),

    },
    {
        Service:   "Heroku",
        Cname:     []string{"herokudns.com", "herokussl.com", "herokuapp.com"},
        Fingerprint: []string{
            "There's nothing here, yet.",
            "herokucdn.com/error-pages/no-such-app.html",
            "<title>No such app</title>",
        },
        Status:  string("Vulnerable"),
        Vulnerable: bool(true),
    },
    */
    {
			  // Vulnerable only in this case:
				// Claim the domain (no errors: the domain is added to domains section correctly)
        Service:   "Unbounce",
        Cname:     []string{"unbouncepages.com"},
        Fingerprint: []string{
            "The requested URL / was not found on this server.",
            "The requested URL was not found on this server",
        },
        Status:  string("Edge Case"),
        Vulnerable: bool(true),

    },
    /*
    {
        Service:   "Tumblr",
        Cname:     []string{"tumblr.com"},
        Fingerprint: []string{
            "There's nothing here.",
            "Whatever you were looking for doesn't currently exist at this address.",
        },
    },
    {
        Service:   "Shopify",
        Cname:     []string{"myshopify.com"},
        Fingerprint: []string{
            "Sorry, this shop is currently unavailable.",
            "Only one step left!",
        },
    },
    {
        Service:   "Zoho",
        Cname:     []string{"zoho.com"},
        Fingerprint: []string{
            "Page not found.",
            "We couldn't find the page you are looking for.",
        },
    },
    */
}
